name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag stern-fluentd-test:$(date +%s)
<<<<<<< HEAD
    - uses: docker/login-action@v1
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: docker/setup-buildx-action@v1
    - name: Set up Docker Buildx
    - uses: docker/build-push-action@v2
    - name: Build and push
      with:
        context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/stern-fluentd-test:${{ env.RELEASE_VERSION }}
=======
>>>>>>> 6c446876e1e2e1c6e47ff51a23e9881ae4d8e5c6
