name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Set env
      uses: actions/checkout@v2
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - 
      name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - 
      name: Build the Docker image
      uses: actions/checkout@v3
      run: docker build . --file Dockerfile --tag stern-fluentd-test:$(date +%s)
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/stern-fluentd-test:${{ env.RELEASE_VERSION }}
